apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-deployment
  labels:
    app: scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper
  template:
    metadata:
      labels:
        app: scraper
    spec:
      containers:
        - name: scraper
          image: harbor.metin.sh/backend/backend:latest
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
            - name: RABBITMQ_HOST
              value: "rabbitmq.rabbitmq.svc.cluster.local"
            - name: KAFKA_CLIENT_ID
              value: "scraper"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "redpanda.redpanda.svc.cluster.local"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5