apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  project: default
  source:
    chart: metallb
    helm:
      values: |
        controller:
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
              labels:
                release: prometheus-stack
          nodeSelector:
            role: master
        speaker:
          metrics:
            serviceMonitor:
              enabled: true
            enabled: true
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: "4.3.0"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: main-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.2.72-192.168.2.72
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advert
  namespace: metallb-system