apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  project: default
  source:
    path: apps/controlplane/system/
    repoURL: https://github.com/MetinSeylan/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true