apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: workload
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.244.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: TalosControlPlane
    name: workload-cp
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: MetalCluster
    name: workload
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: MetalCluster
metadata:
  name: workload
  namespace: default
spec:
  controlPlaneEndpoint:
    host: 10.0.0.108
    port: 6443
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: MetalMachineTemplate
metadata:
  name: workload-cp
  namespace: default
spec:
  template:
    spec:
      serverClassRef:
        apiVersion: metal.sidero.dev/v1alpha1
        kind: ServerClass
        name: any
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: workload-cp
  namespace: default
spec:
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      talosVersion: v1.3.6
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: MetalMachineTemplate
    name: workload-cp
  replicas: 1
  version: v1.26.3
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: workload-workers
  namespace: default
spec:
  template:
    spec:
      generateType: join
      talosVersion: v1.3.6
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: workload-workers
  namespace: default
spec:
  clusterName: workload
  replicas: 0
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: TalosConfigTemplate
          name: workload-workers
      clusterName: workload
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: MetalMachineTemplate
        name: workload-workers
      version: v1.26.3
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: MetalMachineTemplate
metadata:
  name: workload-workers
  namespace: default
spec:
  template:
    spec:
      serverClassRef:
        apiVersion: metal.sidero.dev/v1alpha1
        kind: ServerClass
        name: any

---
apiVersion: metal.sidero.dev/v1alpha1
kind: Server
metadata:
  finalizers:
    - storage.finalizers.server.k8s.io
  generation: 1
  name: cad832c4-40f4-4b61-adee-dd277748c621
spec:
  accepted: true
  configPatches:
    - op: replace
      path: /machine/install/disk
      value: /dev/sda
  cpu:
    manufacturer: QEMU
    version: pc-i440fx-7.1
  hostname: 10.0.0.108
  system:
    family: Unknown
    manufacturer: QEMU
    productName: Standard PC (i440FX + PIIX, 1996)
    serialNumber: Unknown
    skuNumber: Unknown
    version: pc-i440fx-7.1