apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: monitoring
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: jaeger
  project: default
  source:
    chart: jaeger
    helm:
      values: |
        allInOne:
          enabled: true
          nodeSelector:
            role: master
    repoURL: https://jaegertracing.github.io/helm-charts
    targetRevision: 0.71.8
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true