- name: Argocd Helm Repo
  shell: helm repo add argo-cd https://argoproj.github.io/argo-helm

- name: Get Homelab Repo
  ansible.builtin.git:
    repo: https://github.com/MetinSeylan/homelab.git
    dest: /home/metin/homelab

- name: Helm dep update
  shell: helm dep update /home/metin/homelab/apps/controlplane/charts/argo-cd/

- name: Install Argocd
  shell: helm install argo-cd -n argo-cd --create-namespace /home/metin/homelab/apps/controlplane/charts/argo-cd/
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Install Argo Deployment Root
  shell: kubectl apply -f /home/metin/homelab/apps/controlplane/deployments/templates/root.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Install Argo System Root
  shell: kubectl apply -f /home/metin/homelab/apps/controlplane/system/templates/root.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf