- name: Argocd Helm Repo
  shell: helm repo add argo-cd https://argoproj.github.io/argo-helm

- name: Get Homelab Repo
  ansible.builtin.git:
    repo: git@github.com:MetinSeylan/homelab.git
    dest: /home/metin/homelab

- name: Helm dep update
  shell: helm dep update /home/metin/homelab/apps/controlplane/charts/argo-cd/