- name: Setup Clusterctl folder for metin User
  file:
    path: "/home/metin/.cluster-api"
    state: directory
    owner: "metin"
    group: "metin"
    mode: 0750

- name: Create clusterctl.yaml file
  file:
    path: "/home/metin/.cluster-api/clusterctl.yaml"
    state: touch

- name: Write clusterctl.yaml file
  copy:
    dest: "/home/metin/.cluster-api/clusterctl.yaml"
    content: |
      providers:
      - name: "talos"
        url: "https://github.com/siderolabs/cluster-api-bootstrap-provider-talos/releases/latest/bootstrap-components.yaml"
        type: "BootstrapProvider"
      - name: "talos"
        url: "https://github.com/siderolabs/cluster-api-control-plane-provider-talos/releases/latest/control-plane-components.yaml"
        type: "ControlPlaneProvider"
      - name: "sidero"
        url: "https://github.com/siderolabs/sidero/releases/latest/infrastructure-components.yaml"
        type: "InfrastructureProvider"


- name: Install Sidero
  shell: clusterctl init -b talos -c talos -i sidero
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
    SIDERO_CONTROLLER_MANAGER_HOST_NETWORK: true
    SIDERO_CONTROLLER_MANAGER_API_ENDPOINT: 10.0.0.10
    SIDERO_CONTROLLER_MANAGER_SIDEROLINK_ENDPOINT: 10.0.0.10
    SIDERO_CONTROLLER_MANAGER_AUTO_ACCEPT_SERVERS: true
    SIDERO_CONTROLLER_MANAGER_AUTO_BMC_SETUP: false