- name: Init Kubernetes Cluster
  shell: kubeadm init --pod-network-cidr 10.244.0.0/16
  args:
    creates: "/etc/kubernetes/admin.conf"

- name: Setup Kubeconfig for {{ k8s_user }} User
  file:
    path: "/home/{{ k8s_user }}/.kube"
    state: directory
    owner: "{{ k8s_user }}"
    group: "{{ k8s_user }}"
    mode: 0750

- name: Copy /etc/kubernetes/admin.conf
  become: yes
  copy:
    src: "/etc/kubernetes/admin.conf"
    dest: "/home/{{ k8s_user }}/.kube/config"
    owner: "{{ k8s_user }}"
    group: "{{ k8s_user }}"
    mode: 0640
    remote_src: yes


- name: Install Calico Pod Network
  shell: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: add label to master
  shell: kubectl label node master role=master
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Creates prometheus directory
  file:
    path: /storage/nvme/prometheus
    state: directory

- name: Creates grafana directory
  file:
    path: /storage/nvme/grafana
    state: directory

- name: Get join token
  shell: sudo kubeadm token create  --print-join-command
  register: kubernetes_join_command

- name: Copy join command to local file.
  become: false
  local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="./temp/kubernetes_join_command" mode=0777

- name: allow master node to schedule pods
  shell: kubectl taint nodes master node-role.kubernetes.io/control-plane:NoSchedule-
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf