- name: Init Kubernetes Cluster
  shell: kubeadm init --cri-socket unix:///run/containerd/containerd.sock
  args:
    creates: "/etc/kubernetes/admin.conf"

- name: Setup Kubeconfig for {{ k8s_user }} User
  file:
    path: "/home/{{ k8s_user }}/.kube"
    state: directory
    owner: "{{ k8s_user }}"
    group: "{{ k8s_user }}"
    mode: 0750

- name: Copy /etc/kubernetes/admin.conf
  become: yes
  copy:
    src: "/etc/kubernetes/admin.conf"
    dest: "/home/{{ k8s_user }}/.kube/config"
    owner: "{{ k8s_user }}"
    group: "{{ k8s_user }}"
    mode: 0640
    remote_src: yes


- name: Get join token
  shell: sudo kubeadm token create  --print-join-command
  register: kubernetes_join_command

- name: Copy join command to local file.
  become: false
  local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="./temp/kubernetes_join_command" mode=0777