apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    chart: grafana
    helm:
      values: |
        persistence:
          type: statefulset
          enabled: true
          accessModes:
              - ReadWriteOnce
          size: 2Gi
          storageClassName: local-storage
          volumeName: grafana-pv
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: "6.52.9"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/grafana
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - controlplane