apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  project: default
  source:
    chart: harbor
    helm:
      values: |
        persistence:
          enabled: true
          persistentVolumeClaim:
            registry:
               existingClaim: harbor-registry-pvc
            database:
               existingClaim: harbor-database-pvc
            redis:
               existingClaim: harbor-redis-pvc

        expose:
            tls:
              enabled: false
            ingress:
              controller: nginx
              annotations:
                kubernetes.io/ingress.class: nginx
                ingress.kubernetes.io/ssl-redirect: "false"
                nginx.ingress.kubernetes.io/ssl-redirect: "false"


              hosts:
                core: harbor-core.metin.sh
                notary: harbor-notary.metin.sh

    repoURL: https://helm.goharbor.io
    targetRevision: "1.12.2"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-db-pv
  namespace: harbor
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /storage/nvme/harbor/database
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - master
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-registry-pv
  namespace: harbor
spec:
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /storage/nvme/harbor/registry
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - master

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-redis-pv
  namespace: harbor
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /storage/nvme/harbor/redis
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - master