apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  project: default
  source:
    chart: harbor
    helm:
      values: |
        persistence:
          enabled: false
        expose:
            ingress:
              hosts:
                core: harbor-core.metin.sh
                notary: harbor-notary.metin.sh

    repoURL: https://helm.goharbor.io
    targetRevision: "1.12.2"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true