apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  project: default
  source:
    chart: ingress-nginx
    helm:
      values: |
        controller:
          replicaCount: 2
          affinity:
           podAntiAffinity:
             preferredDuringSchedulingIgnoredDuringExecution:
             - weight: 100
               podAffinityTerm:
                 labelSelector:
                   matchExpressions:
                   - key: app.kubernetes.io/name
                     operator: In
                     values:
                     - ingress-nginx
                 topologyKey: kubernetes.io/hostname
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
              additionalLabels:
                release: prometheus-stack
          nodeSelector:
            worker: "true"
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: "4.6.0"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true