apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  project: default
  source:
    chart: keycloak
    helm:
      values: |
        postgres:
          enabled: true
          auth:
            postgresPassword: "keycloak"
            username: "keycloak"
            password: "keycloak"
            database: "keycloak"
          storageClass: local-storage
          persistence:
            enabled: true
            size: 4Gi
            existingClaim: keycloak-pv
            storageClass: local-storage
          nodeSelector:
            role: master
        nodeSelector:
          role: master
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 15.1.6
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-pv
  namespace: keycloak
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /storage/nvme/keycloak_postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - master