apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  project: default
  source:
    chart: keycloak
    helm:
      values: |
        extraEnvVars:
          KC_HTTP_ENABLED: "true"
          KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
          KC_HOSTNAME_STRICT: "true"
          KC_STRICT_HTTPS: "false"
          KC_HOSTNAME: "sso.metin.sh"
        production: true
        proxy: edge
        postgresql:
          enabled: true
          auth:
            postgresPassword: "keycloak"
            username: "keycloak"
            password: "keycloak"
            database: "keycloak"
          storageClass: local-storage
          primary:
            persistence:
              enabled: true
              existingClaim: keycloak-pv-claim
              storageClass: local-storage
            nodeSelector:
              role: master
        nodeSelector:
          role: master
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 15.1.6
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-pv
  namespace: keycloak
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /storage/nvme/keycloak_postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - master
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-pv-claim
  namespace: keycloak
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: keycloak-pv

---
kind: Service
apiVersion: v1
metadata:
  name: keycloak
  namespace: ingress-nginx
spec:
  type: ExternalName
  externalName: keycloak.keycloak.svc.cluster.local
  ports:
    - port: 80