apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  project: default
  source:
    chart: oauth2-proxy
    helm:
      values: |
        configuration:
          content: |
            provider = "keycloak-oidc"
            client-id = "homelab"
            client-secret = "5acWC1AgeHqMHoxDMFYXvNTRFp8ogMTX"
            redirect-url = "https://auth.metin.sh/oauth2/callback"
            oidc-issuer-url = "https://sso.metin.sh/auth/realms/master"
        nodeSelector:
          worker: "true"
        redis:
          enabled: false
        ingress:
          enabled: true
          certManager: false
          annotations:
            kubernetes.io/ingress.class: nginx
          hostname: auth.metin.sh
          tls: true
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: "3.7.4"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true