apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  project: default
  source:
    chart: oauth2-proxy
    helm:
      values: |
        config:
          clientID: "homelab"
        nodeSelector:
          worker: "true"
    repoURL: https://oauth2-proxy.github.io/manifests
    targetRevision: "6.13.1"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
kind: Service
apiVersion: v1
metadata:
  name: oauth2-proxy
  namespace: ingress-nginx
spec:
  type: ExternalName
  externalName: oauth2-proxy.keycloak.svc.cluster.local
  ports:
    - port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-public
  namespace: ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: sso.metin.sh
      http:
        paths:
          - path: /oauth2(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: oauth2-proxy
                port:
                  number: 80
          - path: /sso(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 80
  ingressClassName: nginx