apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  project: default
  source:
    chart: oauth2-proxy
    helm:
      values: |
        config:
          clientID: "homelab"
        nodeSelector:
          worker: "true"
        ingress:
          enabled: true
          certManager: false
          annotations:
            kubernetes.io/ingress.class: nginx
          hostname: auth.metin.sh
          tls: true
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: "6.13.1"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true