apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: postgres
    name: postgres
  name: postgres

---
apiVersion: stackgres.io/v1
kind: SGInstanceProfile
metadata:
  name: coordinator-profile
  namespace: stackgres
spec:
  cpu: 500m
  memory: 2Gi

---
apiVersion: stackgres.io/v1
kind: SGInstanceProfile
metadata:
  name: worker-profile
  namespace: stackgres
spec:
  cpu: 1000m
  memory: 4Gi

---
apiVersion: stackgres.io/v1
kind: SGPostgresConfig
metadata:
  name: coordinator-config
  namespace: stackgres
spec:
  postgresVersion: "15"
  postgresql.conf:
    shared_buffers: "512MB"
    random_page_cost: "1.5"

---
apiVersion: stackgres.io/v1alpha1
kind: SGShardedCluster
metadata:
  name: stackgres
  namespace: stackgres
spec:
  type: 'citus'
  database: 'postgres'
  postgres:
    version: 'latest'
  coordinator:
    instances: 1
    pods:
      persistentVolume:
        size: '1Gi'
  shards:
    clusters: 2
    instancesPerCluster: 1
    pods:
      persistentVolume:
        size: '2Gi'

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: stackgres
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /storage/nvme
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv2
  namespace: stackgres
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /storage/nvme
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node2