apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    chart: prometheus
    helm:
      values: |
        prometheus-pushgateway:
          enabled: false
        alertmanager:
          enabled: false
        retention: 1d
        server:
            statefulSet:
              enabled: true
            persistentVolume:
              enabled: true
              volumeName: prometheus-pv
              size: 8Gi
              storageClass: local-storage
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 19.0.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  namespace: default
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /storage/nvme/prometheus
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - master