apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq
  project: default
  source:
    chart: rabbitmq
    helm:
      values: |
        auth:
          username: guest
          password: guest
        persistence:
          enabled: true
          existingClaim: rabbitmq-pvc
        nodeSelector:
          role: node2
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
            namespace: rabbitmq
            additionalLabels:
              release: rabbitmq
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: "12.0.4"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv
  namespace: rabbitmq
spec:
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /storage/nvme/rabbitmq
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
  namespace: rabbitmq
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: rabbitmq-pv