apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redpanda
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: redpanda
  project: default
  source:
    chart: redpanda
    helm:
      values: |
        console:
          enabled: true
        tls:
          enabled: false
        external:
          enabled: false
        monitoring:
          enabled: true
        statefulset:
          replicas: 2
    repoURL: https://charts.redpanda.com/redpanda
    targetRevision: "*"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true