apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: stackgres
    name: stackgres
  name: stackgres

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stackgres
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: stackgres
  project: default
  source:
    chart: stackgres-operator
    helm:
      values: |
        grafana:
          autoEmbed: true
          webHost: "prometheus-stack-grafana.monitoring.svc"
        operator:
          nodeSelector:
            role: master
        restapi:
          nodeSelector:
            role: master
        jobs:
          nodeSelector:
            role: master
    repoURL: https://stackgres.io/downloads/stackgres-k8s/stackgres/helm/
    targetRevision: 1.5.0-RC1
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true