apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: default
  source:
    chart: vault
    helm:
      values: |
        global:
          enabled: true
        injector:
          nodeSelector:
            role: master
        server:
          nodeSelector:
            role: master
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.24.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true